---
grails:
    profile: web-plugin
    codegen:
        defaultPackage: au.org.ala.bootstrap3
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
