grails:
    plugins:
        twitterbootstrap:
            fixtaglib: true

headerAndFooter:
    baseURL: https://www.ala.org.au/commonui-bs3

userdetails:
    url: https://auth.ala.org.au/userdetails/
    profilePath: myprofile